title:        'hello.'
tagline:      'omni blogs'
description:  'this is a programming blog, capiche?'
url:          http://omnigoat.github.io
version:      1.1.1
author:
  name:       'jona'
  email:      ''
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
permalink:    pretty
paginate: 2
plugins: [jekyll-paginate]
include: [.well-known]
defaults:
  - scope:
      path: "assets/img"
    values:
      image: true