title:        'hello.'
tagline:      'omni blogs'
description:  'this is a programming blog'
url:          http://omnigoat.github.io
version:      1.1.1
author:
  name:       ''
  email:      ''
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
permalink:    pretty
paginate: 2
plugins: [jekyll-paginate]